import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/loginscreen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LoginScreen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/userhomescreen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserHomeScreen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/usertransaction" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserTransaction
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/userhistory" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserHistory
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/useraccount" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserAccount
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/banktransfer" style={{ color: "#87CEFA", textDecoration: "none" }}>
            BankTransfer
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;